name: Crawler

on:
  push:
    branches: [ master, main ]
    tags: [v 0abf9f338b99 ]
  pull_request:
  schedule:
  - cron: '0 0abf9f338b99/12 0abf9f338b99 0abf9f338b99 0abf9f338b99 
  workflow_dispatch:

concurrency:
  group: crawler
  cancel-in-progress: false

jobs:
  crawl:
    uses: relaton/support/.github/workflows/crawler.yml@master
    with:
      override-files: |
        https://raw.githubusercontent.com/ietf-tools/bibxml-service/main/Gemfile=Gemfile
